#!/usr/bin/env ruby

dir = File.expand_path File.dirname(__FILE__)
Dir.chdir("#{dir}/home")

Dir["*"].each do |file|
  target = File.expand_path File.join("~", ".#{file}")
  puts "linking #{target}"
  `rm -rf #{target}`
  `ln -s #{File.expand_path file} #{target}`
end

# Ensure ~/.zshrc.local exists for machine-specific overrides (not symlinked)
zshrc_local = File.expand_path "~/.zshrc.local"
unless File.exist?(zshrc_local)
  puts "touching #{zshrc_local}"
  `touch #{zshrc_local}`
end

unless File.exist?(File.expand_path "~/.vim/autoload/plug.vim")
  puts %x[curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim]
  puts "run `vim +PlugInstall +qall`"
end

# git push on commit
# `echo 'git push' > .git/hooks/post-commit`
# `chmod 755 .git/hooks/post-commit`

# https://alexpearce.me/2014/05/italics-in-iterm2-vim-tmux/
`tic ../terminfo/xterm-256color-italic.terminfo`

`tic -o ~/.terminfo ../terminfo/tmux.terminfo`
`tic -o ~/.terminfo ../terminfo/tmux-256color.terminfo`

`tic -o ~/.terminfo ../terminfo/xterm-256color.terminfo`

# git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
