#!/usr/bin/env ruby

Dir['~/bin/dotfiles/home/*'].each do |file|
  target = File.expand_path File.join(home, ".#{file}")
  puts "linking #{target}"
  `rm -rf #{target}`
  `ln -s #{File.expand_path file} #{target}`
end

`~/bin/dotfiles/install-bash`

# git push on commit
# `echo 'git push' > .git/hooks/post-commit`
# `chmod 755 .git/hooks/post-commit`

