#!/usr/bin/env ruby

dir = File.expand_path File.dirname(__FILE__)
Dir.chdir("#{dir}/home")

Dir["*"].each do |file|
  target = File.expand_path File.join("~", ".#{file}")
  puts "linking #{target}"
  `rm -rf #{target}`
  `ln -s #{File.expand_path file} #{target}`
end

# git push on commit
# `echo 'git push' > .git/hooks/post-commit`
# `chmod 755 .git/hooks/post-commit`
