# If not running interactively, don't do anything
[ -z "$PS1" ] && return

export DOTFILES="$HOME/bin/dotfiles"

. $DOTFILES/bash/env
. $DOTFILES/bash/colors
. $DOTFILES/bash/git
. $DOTFILES/bash/aliases
. $DOTFILES/bash/functions
. $DOTFILES/bash/vbox_functions

. $DOTFILES/bash/scripts

shopt -s histappend
shopt -s checkwinsize

if [[ -f "$HOME/.bashrc.local" ]]; then
  . "$HOME/.bashrc.local"
fi

. $DOTFILES/bash/config
