# If not running interactively, don't do anything
[ -z "$PS1" ] && return

export DOTFILES="$HOME/.dotfiles/companygardener"

. $DOTFILES/sh/aliases

. $DOTFILES/bash/env
. $DOTFILES/bash/colors
. $DOTFILES/bash/git
. $DOTFILES/bash/aliases
. $DOTFILES/bash/functions
. $DOTFILES/bash/vbox_functions

. $DOTFILES/bash/scripts

shopt -s checkwinsize
shopt -s cmdhist
shopt -s histappend

if [[ -f "$HOME/.bashrc.local" ]]; then
  . "$HOME/.bashrc.local"
fi

. $DOTFILES/bash/config
