# ~/.bash_profile
# This file is read for login shells.

# Environment variables
[[ -e ~/.bash_env ]] && source ~/.bash_env || true

# Initialization shared with zsh
[[ -e ~/.profile ]] && source ~/.profile || true

# Bash-specific initialization

# Local bash-specific variables
[[ -e ~/.bash_profile.local ]] && source ~/.bash_profile.local || true

# Also source bashrc if we're interactive
[[ -n $PS1 ]] && [[ -e ~/.bashrc ]] && source ~/.bashrc

# vim: ft=sh
