if [[ -n "$PS1" ]] ; then
  . ~/bin/dotfiles/bash/env
  . ~/bin/dotfiles/bash/colors
  . ~/bin/dotfiles/bash/git
  . ~/bin/dotfiles/bash/config
  . ~/bin/dotfiles/bash/aliases
  . ~/bin/dotfiles/bash/functions
  . ~/bin/dotfiles/bash/vbox_functions

  . ~/bin/dotfiles/bash/scripts

  shopt -s histappend
  shopt -s checkwinsize
fi

if [[ -f "$HOME/.bashrc.local" ]]; then
  . "$HOME/.bashrc.local"
fi

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
