install ag
install bash-completion
install beanstalk
install brew-cask
install chruby
install ctags
install elixir
install gdbm
install git
install htop-osx
install libffi
install libxml2
install libyaml
install macvim
install memcached
install node
install openssl
install ossp-uuid
install par
install postgresql
install python
install python3
install readline
install redis
install ruby-install
install ssh-copy-id
install tree
install vim
install wget

tap caskroom/homebrew-cask

cask install atom
cask install dropbox
cask install iterm2
cask install xquartz

# cask install google-chrome
# cask install transmission

linkapps
