if filereadable(expand("~/.gvimrc.before"))
  source ~/.gvimrc.before
endif

if has("autocmd")
  autocmd VimResized * wincmd =
endif

if filereadable(expand("~/.gvimrc.after"))
  source ~/.gvimrc.after
endif
