set -g prefix C-f
set -g mouse on

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

set -g history-limit 10000
set -s escape-time 0
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
