set nocompatible
if filereadable(expand("~/.vimrc.before"))
  source ~/.vimrc.before
endif

call plug#begin('~/.vim/plugged')

" Colors
Plug 'altercation/vim-colors-solarized'
Plug 'git@github-private:companygardener/vim-tungsten'
Plug 'jpo/vim-railscasts-theme'
Plug 'nanotech/jellybeans.vim'
Plug 'vim-scripts/vanzan_color'
Plug 'w0ng/vim-hybrid'

" Languages
Plug 'rhysd/vim-llvm'
Plug 'cakebaker/scss-syntax.vim'
Plug 'chrisbra/csv.vim'
Plug 'depuracao/vim-rdoc'
Plug 'elixir-lang/vim-elixir'
Plug 'groenewege/vim-less'
Plug 'guns/vim-clojure-static'
Plug 'jimenezrick/vimerl'
Plug 'fatih/vim-go'
Plug 'JuliaLang/julia-vim'
Plug 'kchmck/vim-coffee-script'
Plug 'mmalecki/vim-node.js'
Plug 'nono/vim-handlebars'
Plug 'nuclearsandwich/fancy-vim'
Plug 'pangloss/vim-javascript'
Plug 'jlcrochet/vim-crystal'
Plug 'rosstimson/scala-vim-support'
Plug 'skwp/vim-rspec'
Plug 'slim-template/vim-slim'
Plug 'sunaku/vim-ruby-minitest'
Plug 'tpope/vim-cucumber'
Plug 'tpope/vim-git'
Plug 'tpope/vim-haml'
Plug 'tpope/vim-liquid'
Plug 'tpope/vim-rails'
Plug 'vim-ruby/vim-ruby'
Plug 'yalesov/vim-emblem'
Plug 'wlangstroth/vim-haskell'
Plug 'ziglang/zig.vim'

" Tools
Plug 'airblade/vim-gitgutter'
Plug 'ap/vim-css-color'
Plug 'godlygeek/tabular'
Plug 'honza/vim-snippets'
Plug 'itspriddle/ZoomWin'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'junegunn/goyo.vim'
Plug 'majutsushi/tagbar'
Plug 'MarcWeber/vim-addon-mw-utils'
Plug 'rizzatti/funcoo.vim'
Plug 'rizzatti/dash.vim'
Plug 'preservim/nerdcommenter'
Plug 'preservim/nerdtree'
Plug 'vim-syntastic/syntastic'
Plug 'tomtom/tlib_vim'
Plug 'tpope/vim-bundler'
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-rake'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-speeddating'
Plug 'tpope/vim-surround'
Plug 'hashivim/vim-terraform'
Plug 'tpope/vim-unimpaired'
Plug 'vim-scripts/dbext.vim'
Plug 'vim-scripts/SyntaxAttr.vim'

" https://github.com/tpope/vim-eunuch
" https://github.com/michaeljsmith/vim-indent-object
"
" packadd matchit
" https://github.com/edsono/vim-matchit

call plug#end()

filetype plugin indent on

function! s:wrap()
  set wrap
  set linebreak
  set textwidth=80
  set nolist
endfunction

if has("autocmd")
  au BufReadPost * if &filetype !~ '^git\c' && line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal! g`\"" | endif
endif

if filereadable(expand("~/.vimrc.after"))
  source ~/.vimrc.after
endif
