set nocompatible
if filereadable(expand("~/.vimrc.before"))
  source ~/.vimrc.before
endif

call plug#begin('~/.vim/plugged')

" AI
Plug 'github/copilot.vim'
Plug 'madox2/vim-ai'

" Colors
Plug 'git@github-private:companygardener/vim-tungsten'
" Plug 'altercation/vim-colors-solarized'
" Plug 'jpo/vim-railscasts-theme'
" Plug 'nanotech/jellybeans.vim'
" Plug 'vim-scripts/vanzan_color'
" Plug 'w0ng/vim-hybrid'

" Languages
Plug 'rhysd/vim-llvm'
Plug 'cakebaker/scss-syntax.vim'
Plug 'chrisbra/csv.vim'
Plug 'elixir-lang/vim-elixir'
Plug 'fatih/vim-go'
Plug 'JuliaLang/julia-vim'
Plug 'MaxMEllon/vim-jsx-pretty'
Plug 'leafgarland/typescript-vim'
Plug 'pangloss/vim-javascript'
Plug 'jlcrochet/vim-crystal'
Plug 'skwp/vim-rspec'
Plug 'slim-template/vim-slim'
Plug 'tpope/vim-cucumber'
Plug 'tpope/vim-git'
Plug 'tpope/vim-haml'
Plug 'tpope/vim-rails'
Plug 'vim-ruby/vim-ruby'
Plug 'wlangstroth/vim-haskell'
Plug 'hashivim/vim-terraform'
Plug 'ziglang/zig.vim'
" Plug 'guns/vim-clojure-static'
" Plug 'kchmck/vim-coffee-script'
" Plug 'jimenezrick/vimerl'
" Plug 'nono/vim-handlebars'
" Plug 'nuclearsandwich/fancy-vim'
" Plug 'joukevandermaas/vim-ember-hbs'
" Plug 'posva/vim-vue'
" Plug 'rosstimson/scala-vim-support'
" Plug 'yalesov/vim-emblem'
" Plug 'depuracao/vim-rdoc'
" Plug 'groenewege/vim-less'
" Plug 'tpope/vim-liquid'
" Plug 'sunaku/vim-ruby-minitest'

" Tools
Plug 'airblade/vim-gitgutter'
Plug 'companygardener/vim-css-color'
Plug 'godlygeek/tabular'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'junegunn/goyo.vim'
Plug 'majutsushi/tagbar'
Plug 'preservim/nerdtree'
Plug 'vim-syntastic/syntastic'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'vim-scripts/SyntaxAttr.vim'
" Plug 'MarcWeber/vim-addon-mw-utils'
" Plug 'tomtom/tlib_vim'
" Plug 'honza/vim-snippets'
" Plug 'rizzatti/funcoo.vim'
" Plug 'rizzatti/dash.vim'
" Plug 'vim-scripts/dbext.vim'
" Plug 'tpope/vim-speeddating'
"
" Plug 'itspriddle/ZoomWin'
" Plug 'preservim/nerdcommenter'
" Plug 'tpope/vim-bundler'
" Plug 'tpope/vim-dispatch'
" Plug 'tpope/vim-rake'

" https://github.com/tpope/vim-eunuch
" https://github.com/michaeljsmith/vim-indent-object
"
" packadd matchit
" https://github.com/edsono/vim-matchit

call plug#end()

filetype plugin indent on

function! s:wrap()
  set wrap
  set linebreak
  set textwidth=80
  set nolist
endfunction

if has("autocmd")
  au BufReadPost * if &filetype !~ '^git\c' && line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal! g`\"" | endif
endif

if filereadable(expand("~/.vimrc.after"))
  source ~/.vimrc.after
endif
