# ~/.zprofile
# This file is read after ~/.zshenv for login shells

# Initialization shared with bash
[[ -e ~/.profile ]] && source ~/.profile || true

# Zsh-specific initialization

# Local zsh-specific variables
[[ -e ~/.zprofile.local ]] && source ~/.zprofile.local || true

# vim: ft=zsh

# chruby
source /opt/homebrew/opt/chruby/share/chruby/chruby.sh
source /opt/homebrew/opt/chruby/share/chruby/auto.sh

# Optional default when not in a project with .ruby-version
chruby 4.0.2
